### ISSUE TITLE
Lock screen keeps swiping up

### ISSUE THREAD

**Issue by ghost** [PFCKrutonium/Windows-10-Login-Background-Changer#39]
Every 5 mins or so the lock screen swipes up and it shows that its trying to log me in and then the lock screen swipes down again and this just keeps happening over and over.

**Comment by Krutonium** [comment]
Are you able to login at all or is this all it does?

**Comment by ghost** [comment]
I can log on when i want to yes but when im away from my computer i can notice this when im doing something else in my room that the lock screen swipes up and the loading symbol appears as if the enter key was pressed and then the lock screen just comes down again

**Comment by Toyz** [comment]
Your PRi is messed up you need to restore the original PRi from your recovery media

**Comment by ghost** [comment]
how do i do that?

**Comment by Toyz** [comment]
You need to put in a recovery media and select "command prompt" and CD into c:\Windows\SystemResources\Windows.UI.Logon and replace Windows.UI.Logon.pri with Windows.UI.Logon.pri.bak

**Comment by ghost** [comment]
I dont have a recovery media...is there another way? or a way i can get a recovery media?

**Comment by Toyz** [comment]
You can use Windows advanced boot options but it's rather hard to access or boot from like a Windows 8 disk

**Comment by ghost** [comment]
how do i do that

**Comment by Toyz** [comment]
Google? I don't know off hand I have a custom console.efi I boot if I crash my system

**Comment by ghost** [comment]
what do i do once i get to the boot?

**Comment by Toyz** [comment]
Like I said I don't know how to get into the advanced boot options off the top of my head cause I have a custom efi file for console access

**Comment by ghost** [comment]
yah ik how to get to the boot but what do i do once i get htere?

**Comment by Toyz** [comment]
You need to select command prompt and then use 

Cd C:\Windows\SystemResources\Windows.UI.Logon
Copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri

You may need to do this first after CD

Del Windows.UI.Logon.pri

**Comment by u0398** [comment]
I had a similar problem. Constant flashing on the welcome screen, with the spinning "working" icon flashing in the middle of the screen. There was no way to login. I was able to get to the windows recovery menu by shutting off the computer mid startup. F8 does not work with a new computer and ssd.

Toyz instructions at the command prompt restored the logon screen. Thank you!

**Comment by ghost** [comment]
I can't even get past the Cd command, gives me, "the system cannot find the path specified". Please help, having the same problem as above. My heart sank when I saw this issue start. Using a Dell XPS 13.

**Comment by ghost** [comment]
If it comes down to it, would doing a reset using "remove apps and settings but keep personal files" fix the problem, or would that not target the 'Windows.UI.Logon.pri' file?

**Comment by tetra-fox** [comment]
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by ghost** [comment]
That didn't help either, constantly getting errors saying the paths cannot be found. Tried to do a refresh but the option wasn't there. Currently waiting on the reset to finish, then a few hours of reinstalls and trying to set up ALL over again.

**Comment by ghost** [comment]
I can't freaking believe this crap. I reset my entire OS and it was completely fine..restarted for updates and this same issue is back. I followed the steps in the wiki step by step and it didn't work the last time. Why would a reset not fix this?!

**Comment by zxzlsh** [comment]
This is how i fixed my problem.

Use these commands (without quotation)

"CD" = "Change Directory"
"CD.." = "Change to the parent directory"
"DIR" = "Display list of files and folders"
"wmic logicaldisk get name" = "List of available drives on the computer"

Step 1
Be sure you are on the correct hard drive.
Type "wmic logicaldisk get name"

You will see a list of available drives.
For example:

C:
D:
E:
X:

Step 2

1- Type "C:"
2- Type "CD Users"
3- Type "DIR"

-If you see your windows 10 folder account name, that mean you are on the correct drive. Go to step 3
-If not, go back to step 1 and try the next available drive.

Step 3

Type:
(Note: Change the first "C" letter with the right hard drive letter)
1- Cd C:\Windows\SystemResources\Windows.UI.Logon
2- Copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri
3- Yes
4- exit

**Comment by ghost** [comment]
I appreciate the help but it still doesn't work. I can Cd into the folder as in step 1, but after step 2, I continue getting "the system cannot find the file specified". I'm fairly certain the "windows.ui.logon.pri.bak" file is missing, not sure how.

**Comment by Toyz** [comment]
That error means your not running the commands as we posted

**Comment by ghost** [comment]
Yes I did, many times. Further more, just to check I did a dir to the "pris" folder and the file isn't called "Windows.UI.Logon.pri" it's "Windows.UI.Logon.en-US.pri". I tried the copy from .bak as well but it still can't be found.

**Comment by Oleg015** [comment]
OK, Please Help. This app is total crap and made may day very bad. So i am a bit frustrated.
What is happened? 
- Lock screen swiping up
- Made a systen restore, Did not helped, last logged user active, and i can-"t logout and log in with any other username about the 3 on that machine 
- copy the required files into an USB stick
- reboot into Command prompt
- realised there no any .bak files
- overwrite files which copied from another Windows 10 machine
- STILL CAN'T CHANGE USER. Last user always log in automatically without prompt for a name, and there is no chance to quit from that user, because Start menu doesn't work anymore

WHAT SHOULD I DO NEXT?

**Comment by tetra-fox** [comment]
@Oleg015 [y'know...](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

**Comment by cracklesparkle** [comment]
@zxzlsh thank you so much, that helped me :)

**Comment by gearcapitan** [comment]
I too feel the same, if I can change the screen where I put my password, but the lock screen that slides up, is damaged and can not see, only a few points listed in a circle and immediately the screen turns to put my password and restore the file Windows.UI.Logon.pri.bak achieved but still nothing works, anyone know how to fix that?

**Comment by emmatyping** [comment]
For posterity `I did a dir to the "pris" folder and the file isn't called "Windows.UI.Logon.pri" it's "Windows.UI.Logon.en-US.pri".` This is the folder **below** the files we are looking for. For those of you who have this problem if you are in that directory, `cd ..` to get to the correct directory.

**Comment by victorscopel** [comment]
Do you have screen saver activated? if not what is the time in it?

I think the problem is the screen saver, even if the screen saver is disabled if the time is 1 minute or 5 min the lock screen will swipe up.

if this doesn't work you can try to remove any app in the lock screen

**Comment by victorscopel** [comment]
The problem is the screensaver, you need to change the time in the settings, even if the screensaver is disabled, it trigger something and the screen swipe up

**Comment by glasody** [comment]
I think I also have the same problem, Ive tried replacing the bak pri, and also grabbing a pri off another of my computers. but no luck..
It only seems to happen before I logon for the first time after boot, once I logon and the computer locks, it sleeps fine, I can wake it up and leave it there and the issue of it looking like its trying to login itself doesn't occur.
